export const EARTH_RADIUS_KM = 6371;
export const DEG_TO_RAD = Math.PI / 180;
export const RAD_TO_DEG = 180 / Math.PI;
export const MAX_FOCUS_DEPTH_KM = 700;
export const MAX_TRAVEL_TIME_SEC = 2500;
export const RAY_FAN_COUNT = 360; // number of takeoff angles
export const MIN_TAKEOFF_DEG = 0.5;
export const MAX_TAKEOFF_DEG = 89.5;
export const INTEGRATION_STEPS = 150;
